# syntax = docker/dockerfile:1.2

FROM emscripten/emsdk

ARG ENV

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y pkg-config

RUN emsdk install tot

ENV EM_CONFIG=/emsdk/.emscripten


