name: Run build and test
# inspired by emscripten-glfw github action so portions copied
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ports
        uses: actions/checkout@v4
        with:
          path: emscripten-wasm-squashfs

      - name: Checkout emscripten
        uses: actions/checkout@v4
        with:
          repository: emscripten-core/emsdk
          path: emscripten

      - name: Install Emscripten
        working-directory: ${{github.workspace}}/emscripten
        run: |
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          emcc -v

      - name: Build and run test for gzip with callback
        working-directory: ${{github.workspace}}/emscripten-wasm-squashfs/test
        run: |
          source ${{github.workspace}}/emscripten/emsdk_env.sh
          ./run_test_gzip_sharedmem.sh

      - name: Build and run test for zstd with callback
        working-directory: ${{github.workspace}}/emscripten-wasm-squashfs/test
        run: |
          source ${{github.workspace}}/emscripten/emsdk_env.sh
          ./run_test_zstd_sharedmem.sh

      - name: Build and run test for gzip
        working-directory: ${{github.workspace}}/emscripten-wasm-squashfs/test
        run: |
          source ${{github.workspace}}/emscripten/emsdk_env.sh
          ./run_test_gzip.sh

      - name: Build and run test for zstd
        working-directory: ${{github.workspace}}/emscripten-wasm-squashfs/test
        run: |
          source ${{github.workspace}}/emscripten/emsdk_env.sh
          ./run_test_zstd.sh


      

      

